### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Andre601** [harry0198/InfoHeads-mvn#6]
Updating to 2.0 gave me the following error on startup:
```
[03:25:37 INFO]: [InfoHeads] Enabling InfoHeads v2.0
[03:25:37 ERROR]: Error occurred while enabling InfoHeads v2.0 (Is it up to date?)
java.lang.NullPointerException: null
        at me.harry0198.infoheads.datastore.DataStore.addToConfig(DataStore.java:71) ~[?:?]
        at me.harry0198.infoheads.datastore.DataStore.addInfoHead(DataStore.java:46) ~[?:?]
        at me.harry0198.infoheads.InfoHeads.lambda$updateConfig$2(InfoHeads.java:152) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at me.harry0198.infoheads.InfoHeads.updateConfig(InfoHeads.java:152) ~[?:?]
        at me.harry0198.infoheads.InfoHeads.load(InfoHeads.java:99) ~[?:?]
        at me.harry0198.infoheads.InfoHeads.onEnable(InfoHeads.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-146]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by harry0198** [comment]
Should have fixed in newest version: https://www.spigotmc.org/resources/infoheads-1-8-1-15-right-click-a-skull-for-information-easy.67080/update?update=324963
